### ISSUE TITLE
Bug: column and bar charts not plotting for 1-row datasets.

### ISSUE THREAD

**Issue by jcrodriguez1989** [dreamRs/toastui#22]
Hi, sorry I didn't take a look at how to solve this issue.
But I think I should let you know about the bug. When the dataset has just one row, the chart never appears. Let me know if you would like to get my sessionInfo.

This is the example you provide, and the non-working version:
```r
library(toastui)
library(ggplot2)
library(dplyr)

# Showing.
count(mpg, class) %>% 
  chart(aes(class, n), type = "column") %>% 
  chart_options(legend = list(visible = FALSE))
# Not showing.
count(mpg, class) %>% 
  slice_head(n = 1) %>%
  chart(aes(class, n), type = "column") %>% 
  chart_options(legend = list(visible = FALSE))
```

**Comment by pvictor** [comment]
Ah yes, thanks for reporting. Should be fixed if you re-install from GitHub.

Victor

**Comment by jcrodriguez1989** [comment]
My bad I didn't try running the dev version.
Thanks for your fast reply!
I confirm it works on dev version.

**Comment by pvictor** [comment]
It wouldn't have worked with the dev version either, I pushed a correction after seeing your message 😉
Don't hesitate to open new issues !

**Comment by jcrodriguez1989** [comment]
Ok, so, new bug (challenge xD) then, still not showing when used inside Shiny.

```r
library(shiny)
library(toastui)
library(ggplot2)
library(dplyr)

ui <- fluidPage(fluidRow(
  column(6, chartOutput("chart_1")),
  column(6, chartOutput("chart_2"))
))

server <- function(input, output, session) {
  output$chart_1 <- renderChart({
    count(mpg, class) %>% 
      chart(aes(class, n), type = "column") %>% 
      chart_options(legend = list(visible = FALSE))
  })
  output$chart_2 <- renderChart({
    count(mpg, class) %>% 
      slice_head(n = 1) %>%
      chart(aes(class, n), type = "column") %>% 
      chart_options(legend = list(visible = FALSE))
  })
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
It works fine for me, maybe restart your session ? And make you're using version `0.2.1.9100`

**Comment by jcrodriguez1989** [comment]
Yup, working, sorry.
And thanks, Victor!!
